# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sandy/Documents/informatique/mes-scripts/projet-exercice-python4/interface_graphique/fenetreprincipale.ui'
#
# Created: Sun Aug 26 17:15:08 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ExercicesPython(object):
    def setupUi(self, ExercicesPython):
        ExercicesPython.setObjectName("ExercicesPython")
        ExercicesPython.resize(703, 906)
        self.fenetreprincipale_2 = QtGui.QWidget(ExercicesPython)
        self.fenetreprincipale_2.setObjectName("fenetreprincipale_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.fenetreprincipale_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_2 = QtGui.QFrame(self.fenetreprincipale_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 0, 1, 3, 1)
        self.Frcoldroite = QtGui.QFrame(self.fenetreprincipale_2)
        self.Frcoldroite.setEnabled(True)
        self.Frcoldroite.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Frcoldroite.setFrameShadow(QtGui.QFrame.Raised)
        self.Frcoldroite.setObjectName("Frcoldroite")
        self.gridLayout = QtGui.QGridLayout(self.Frcoldroite)
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtGui.QFrame(self.Frcoldroite)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 3)
        self.btn_5lignes = QtGui.QPushButton(self.Frcoldroite)
        self.btn_5lignes.setEnabled(True)
        font = QtGui.QFont()
        self.btn_5lignes.setFont(font)
        self.btn_5lignes.setCheckable(False)
        self.btn_5lignes.setDefault(False)
        self.btn_5lignes.setObjectName("btn_5lignes")
        self.gridLayout.addWidget(self.btn_5lignes, 4, 0, 1, 1)
        self.la_enonce = QtGui.QLabel(self.Frcoldroite)
        self.la_enonce.setEnabled(True)
        self.la_enonce.setObjectName("la_enonce")
        self.gridLayout.addWidget(self.la_enonce, 0, 0, 1, 1)
        self.te_contenu = QtGui.QTextEdit(self.Frcoldroite)
        self.te_contenu.setObjectName("te_contenu")
        self.gridLayout.addWidget(self.te_contenu, 3, 0, 1, 3)
        self.btn_reussite = QtGui.QPushButton(self.Frcoldroite)
        self.btn_reussite.setObjectName("btn_reussite")
        self.gridLayout.addWidget(self.btn_reussite, 6, 1, 1, 1)
        self.btn_10lignes = QtGui.QPushButton(self.Frcoldroite)
        self.btn_10lignes.setEnabled(True)
        self.btn_10lignes.setObjectName("btn_10lignes")
        self.gridLayout.addWidget(self.btn_10lignes, 4, 1, 1, 1)
        self.te_enonce = QtGui.QTextEdit(self.Frcoldroite)
        self.te_enonce.setEnabled(True)
        self.te_enonce.setObjectName("te_enonce")
        self.gridLayout.addWidget(self.te_enonce, 1, 0, 1, 3)
        self.btn_faire = QtGui.QPushButton(self.Frcoldroite)
        self.btn_faire.setObjectName("btn_faire")
        self.gridLayout.addWidget(self.btn_faire, 6, 0, 1, 1)
        self.la_contenu = QtGui.QLabel(self.Frcoldroite)
        self.la_contenu.setEnabled(True)
        self.la_contenu.setObjectName("la_contenu")
        self.gridLayout.addWidget(self.la_contenu, 2, 0, 1, 1)
        self.btn_toutvoir = QtGui.QPushButton(self.Frcoldroite)
        self.btn_toutvoir.setObjectName("btn_toutvoir")
        self.gridLayout.addWidget(self.btn_toutvoir, 4, 2, 1, 1)
        self.gridLayout_6.addWidget(self.Frcoldroite, 0, 2, 3, 1)
        self.Frcolgauche = QtGui.QFrame(self.fenetreprincipale_2)
        self.Frcolgauche.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Frcolgauche.setFrameShadow(QtGui.QFrame.Raised)
        self.Frcolgauche.setObjectName("Frcolgauche")
        self.gridLayout_7 = QtGui.QGridLayout(self.Frcolgauche)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtGui.QFrame(self.Frcolgauche)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listwid_fichier = QtGui.QListWidget(self.frame_4)
        self.listwid_fichier.setObjectName("listwid_fichier")
        self.horizontalLayout.addWidget(self.listwid_fichier)
        self.listreussi_fichier = QtGui.QListWidget(self.frame_4)
        self.listreussi_fichier.setObjectName("listreussi_fichier")
        self.horizontalLayout.addWidget(self.listreussi_fichier)
        self.gridLayout_7.addWidget(self.frame_4, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.Frcolgauche)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 1, 0, 1, 1)
        self.Fradiobouton = QtGui.QFrame(self.Frcolgauche)
        self.Fradiobouton.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Fradiobouton.setFrameShadow(QtGui.QFrame.Raised)
        self.Fradiobouton.setObjectName("Fradiobouton")
        self.gridLayout_4 = QtGui.QGridLayout(self.Fradiobouton)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.GBradiobt = QtGui.QGroupBox(self.Fradiobouton)
        self.GBradiobt.setObjectName("GBradiobt")
        self.gridLayout_2 = QtGui.QGridLayout(self.GBradiobt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radbout_interme = QtGui.QRadioButton(self.GBradiobt)
        self.radbout_interme.setObjectName("radbout_interme")
        self.gridLayout_2.addWidget(self.radbout_interme, 1, 1, 1, 1)
        self.radbout_expert = QtGui.QRadioButton(self.GBradiobt)
        self.radbout_expert.setObjectName("radbout_expert")
        self.gridLayout_2.addWidget(self.radbout_expert, 1, 2, 1, 1)
        self.radbout_debut = QtGui.QRadioButton(self.GBradiobt)
        self.radbout_debut.setObjectName("radbout_debut")
        self.gridLayout_2.addWidget(self.radbout_debut, 1, 0, 1, 1)
        self.radbout_toutniv = QtGui.QRadioButton(self.GBradiobt)
        self.radbout_toutniv.setChecked(True)
        self.radbout_toutniv.setObjectName("radbout_toutniv")
        self.gridLayout_2.addWidget(self.radbout_toutniv, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.GBradiobt, 0, 0, 1, 1)
        self.GBvisuali = QtGui.QGroupBox(self.Fradiobouton)
        self.GBvisuali.setObjectName("GBvisuali")
        self.gridLayout_3 = QtGui.QGridLayout(self.GBvisuali)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btexerfaire = QtGui.QRadioButton(self.GBvisuali)
        self.btexerfaire.setObjectName("btexerfaire")
        self.gridLayout_3.addWidget(self.btexerfaire, 2, 2, 1, 1)
        self.btexerreussi = QtGui.QRadioButton(self.GBvisuali)
        self.btexerreussi.setObjectName("btexerreussi")
        self.gridLayout_3.addWidget(self.btexerreussi, 2, 0, 1, 1)
        self.btexertout = QtGui.QRadioButton(self.GBvisuali)
        self.btexertout.setChecked(True)
        self.btexertout.setObjectName("btexertout")
        self.gridLayout_3.addWidget(self.btexertout, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.GBvisuali, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.Fradiobouton, 0, 0, 1, 1)
        self.progressBar1 = QtGui.QProgressBar(self.Frcolgauche)
        self.progressBar1.setProperty("value", 0)
        self.progressBar1.setObjectName("progressBar1")
        self.gridLayout_7.addWidget(self.progressBar1, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.Frcolgauche, 0, 0, 3, 1)
        ExercicesPython.setCentralWidget(self.fenetreprincipale_2)
        self.menubar = QtGui.QMenuBar(ExercicesPython)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 22))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuCr_er_un_exercice = QtGui.QMenu(self.menubar)
        self.menuCr_er_un_exercice.setObjectName("menuCr_er_un_exercice")
        self.menuChanger_le_th_me = QtGui.QMenu(self.menubar)
        self.menuChanger_le_th_me.setObjectName("menuChanger_le_th_me")
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        ExercicesPython.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ExercicesPython)
        self.statusbar.setObjectName("statusbar")
        ExercicesPython.setStatusBar(self.statusbar)
        self.actionOuvrir_un_fichier = QtGui.QAction(ExercicesPython)
        self.actionOuvrir_un_fichier.setObjectName("actionOuvrir_un_fichier")
        self.actionSauvegarder_un_fichier = QtGui.QAction(ExercicesPython)
        self.actionSauvegarder_un_fichier.setObjectName("actionSauvegarder_un_fichier")
        self.actionFerm_fich = QtGui.QAction(ExercicesPython)
        self.actionFerm_fich.setObjectName("actionFerm_fich")
        self.actionCreer_exercice = QtGui.QAction(ExercicesPython)
        self.actionCreer_exercice.setObjectName("actionCreer_exercice")
        self.actionModifier_exercices = QtGui.QAction(ExercicesPython)
        self.actionModifier_exercices.setObjectName("actionModifier_exercices")
        self.actionSupprimer_exercices = QtGui.QAction(ExercicesPython)
        self.actionSupprimer_exercices.setObjectName("actionSupprimer_exercices")
        self.actionTheme_clair = QtGui.QAction(ExercicesPython)
        self.actionTheme_clair.setObjectName("actionTheme_clair")
        self.actionTheme_sombre = QtGui.QAction(ExercicesPython)
        self.actionTheme_sombre.setObjectName("actionTheme_sombre")
        self.actionAide_log = QtGui.QAction(ExercicesPython)
        self.actionAide_log.setObjectName("actionAide_log")
        self.action_Apropos = QtGui.QAction(ExercicesPython)
        self.action_Apropos.setObjectName("action_Apropos")
        self.menuFichier.addAction(self.actionFerm_fich)
        self.menuCr_er_un_exercice.addAction(self.actionCreer_exercice)
        self.menuCr_er_un_exercice.addAction(self.actionModifier_exercices)
        self.menuCr_er_un_exercice.addAction(self.actionSupprimer_exercices)
        self.menuChanger_le_th_me.addAction(self.actionTheme_clair)
        self.menuChanger_le_th_me.addAction(self.actionTheme_sombre)
        self.menuAide.addAction(self.actionAide_log)
        self.menuAide.addAction(self.action_Apropos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuCr_er_un_exercice.menuAction())
        self.menubar.addAction(self.menuChanger_le_th_me.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(ExercicesPython)
        QtCore.QMetaObject.connectSlotsByName(ExercicesPython)

    def retranslateUi(self, ExercicesPython):
        ExercicesPython.setWindowTitle(QtGui.QApplication.translate("ExercicesPython", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_5lignes.setText(QtGui.QApplication.translate("ExercicesPython", "Voir 5 lignes", None, QtGui.QApplication.UnicodeUTF8))
        self.la_enonce.setText(QtGui.QApplication.translate("ExercicesPython", "Énoncé : ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reussite.setText(QtGui.QApplication.translate("ExercicesPython", "j\'ai réussi ! ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_10lignes.setText(QtGui.QApplication.translate("ExercicesPython", "Voir 10 lignes", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_faire.setText(QtGui.QApplication.translate("ExercicesPython", "À refaire", None, QtGui.QApplication.UnicodeUTF8))
        self.la_contenu.setText(QtGui.QApplication.translate("ExercicesPython", "Solution : ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_toutvoir.setText(QtGui.QApplication.translate("ExercicesPython", "tout voir", None, QtGui.QApplication.UnicodeUTF8))
        self.GBradiobt.setTitle(QtGui.QApplication.translate("ExercicesPython", "Niveaux", None, QtGui.QApplication.UnicodeUTF8))
        self.radbout_interme.setText(QtGui.QApplication.translate("ExercicesPython", "Intermédiaire", None, QtGui.QApplication.UnicodeUTF8))
        self.radbout_expert.setText(QtGui.QApplication.translate("ExercicesPython", "Expert", None, QtGui.QApplication.UnicodeUTF8))
        self.radbout_debut.setText(QtGui.QApplication.translate("ExercicesPython", "Débutant", None, QtGui.QApplication.UnicodeUTF8))
        self.radbout_toutniv.setText(QtGui.QApplication.translate("ExercicesPython", "Tous les niveaux", None, QtGui.QApplication.UnicodeUTF8))
        self.GBvisuali.setTitle(QtGui.QApplication.translate("ExercicesPython", "Visualisation exercices", None, QtGui.QApplication.UnicodeUTF8))
        self.btexerfaire.setText(QtGui.QApplication.translate("ExercicesPython", "À faire", None, QtGui.QApplication.UnicodeUTF8))
        self.btexerreussi.setText(QtGui.QApplication.translate("ExercicesPython", "Réussis", None, QtGui.QApplication.UnicodeUTF8))
        self.btexertout.setText(QtGui.QApplication.translate("ExercicesPython", "Tous les exercices", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("ExercicesPython", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCr_er_un_exercice.setTitle(QtGui.QApplication.translate("ExercicesPython", "Les exercices", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChanger_le_th_me.setTitle(QtGui.QApplication.translate("ExercicesPython", "Changer le thème", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("ExercicesPython", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOuvrir_un_fichier.setText(QtGui.QApplication.translate("ExercicesPython", "Ouvrir un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSauvegarder_un_fichier.setText(QtGui.QApplication.translate("ExercicesPython", "Sauvegarder un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFerm_fich.setText(QtGui.QApplication.translate("ExercicesPython", "Fermer le fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreer_exercice.setText(QtGui.QApplication.translate("ExercicesPython", "Créer un exercice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModifier_exercices.setText(QtGui.QApplication.translate("ExercicesPython", "Modifier un exercice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSupprimer_exercices.setText(QtGui.QApplication.translate("ExercicesPython", "Supprimer un exercice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheme_clair.setText(QtGui.QApplication.translate("ExercicesPython", "Thème clair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheme_sombre.setText(QtGui.QApplication.translate("ExercicesPython", "Thème sombre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAide_log.setText(QtGui.QApplication.translate("ExercicesPython", "Aide sur le logiciel", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Apropos.setText(QtGui.QApplication.translate("ExercicesPython", "À propos", None, QtGui.QApplication.UnicodeUTF8))

