# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sandy/Documents/informatique/mes-scripts/projet-python-exercice1/interfacegraph/interface_graph.ui'
#
# Created: Mon Jun 11 08:05:21 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ExercicePython(object):
    def setupUi(self, ExercicePython):
        ExercicePython.setObjectName("ExercicePython")
        ExercicePython.resize(998, 702)
        self.centralwidget = QtGui.QWidget(ExercicePython)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 2, 2, 1)
        self.gridLayout_contenu = QtGui.QGridLayout()
        self.gridLayout_contenu.setObjectName("gridLayout_contenu")
        self.la_enonce = QtGui.QLabel(self.centralwidget)
        self.la_enonce.setObjectName("la_enonce")
        self.gridLayout_contenu.addWidget(self.la_enonce, 0, 0, 1, 1)
        self.te_solution = QtGui.QTextEdit(self.centralwidget)
        self.te_solution.setObjectName("te_solution")
        self.gridLayout_contenu.addWidget(self.te_solution, 4, 0, 1, 1)
        self.te_enonce = QtGui.QTextEdit(self.centralwidget)
        self.te_enonce.setObjectName("te_enonce")
        self.gridLayout_contenu.addWidget(self.te_enonce, 1, 0, 1, 1)
        self.la_solution = QtGui.QLabel(self.centralwidget)
        self.la_solution.setObjectName("la_solution")
        self.gridLayout_contenu.addWidget(self.la_solution, 3, 0, 1, 1)
        self.horizontalLayout_btn_cont = QtGui.QHBoxLayout()
        self.horizontalLayout_btn_cont.setObjectName("horizontalLayout_btn_cont")
        self.btn_toutvoir = QtGui.QPushButton(self.centralwidget)
        self.btn_toutvoir.setObjectName("btn_toutvoir")
        self.horizontalLayout_btn_cont.addWidget(self.btn_toutvoir)
        self.btn_5lignes = QtGui.QPushButton(self.centralwidget)
        self.btn_5lignes.setObjectName("btn_5lignes")
        self.horizontalLayout_btn_cont.addWidget(self.btn_5lignes)
        self.btn_10lignes = QtGui.QPushButton(self.centralwidget)
        self.btn_10lignes.setObjectName("btn_10lignes")
        self.horizontalLayout_btn_cont.addWidget(self.btn_10lignes)
        self.gridLayout_contenu.addLayout(self.horizontalLayout_btn_cont, 5, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_contenu, 1, 3, 1, 1)
        self.groupBox_nomfiche = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_nomfiche.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_nomfiche.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_nomfiche.setObjectName("groupBox_nomfiche")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_nomfiche)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_niveau = QtGui.QHBoxLayout()
        self.horizontalLayout_niveau.setObjectName("horizontalLayout_niveau")
        self.rb_deb = QtGui.QRadioButton(self.groupBox_nomfiche)
        self.rb_deb.setObjectName("rb_deb")
        self.horizontalLayout_niveau.addWidget(self.rb_deb)
        self.rb_int = QtGui.QRadioButton(self.groupBox_nomfiche)
        self.rb_int.setObjectName("rb_int")
        self.horizontalLayout_niveau.addWidget(self.rb_int)
        self.rb_exp = QtGui.QRadioButton(self.groupBox_nomfiche)
        self.rb_exp.setObjectName("rb_exp")
        self.horizontalLayout_niveau.addWidget(self.rb_exp)
        self.gridLayout.addLayout(self.horizontalLayout_niveau, 0, 0, 1, 1)
        self.liste_fiche = QtGui.QListWidget(self.groupBox_nomfiche)
        self.liste_fiche.setObjectName("liste_fiche")
        self.gridLayout.addWidget(self.liste_fiche, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_nomfiche, 0, 0, 2, 2)
        ExercicePython.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ExercicePython)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 22))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.Creer_fiche = QtGui.QMenu(self.menubar)
        self.Creer_fiche.setObjectName("Creer_fiche")
        self.changer_theme = QtGui.QMenu(self.menubar)
        self.changer_theme.setObjectName("changer_theme")
        self.menuA_propos = QtGui.QMenu(self.menubar)
        self.menuA_propos.setObjectName("menuA_propos")
        ExercicePython.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ExercicePython)
        self.statusbar.setObjectName("statusbar")
        ExercicePython.setStatusBar(self.statusbar)
        self.ouv_fichier = QtGui.QAction(ExercicePython)
        self.ouv_fichier.setObjectName("ouv_fichier")
        self.sauv_fichier = QtGui.QAction(ExercicePython)
        self.sauv_fichier.setObjectName("sauv_fichier")
        self.fermer_fichier = QtGui.QAction(ExercicePython)
        self.fermer_fichier.setObjectName("fermer_fichier")
        self.theme_clair = QtGui.QAction(ExercicePython)
        self.theme_clair.setObjectName("theme_clair")
        self.theme_sombre = QtGui.QAction(ExercicePython)
        self.theme_sombre.setObjectName("theme_sombre")
        self.aide_logiciel = QtGui.QAction(ExercicePython)
        self.aide_logiciel.setObjectName("aide_logiciel")
        self.a_propos = QtGui.QAction(ExercicePython)
        self.a_propos.setObjectName("a_propos")
        self.menuFichier.addAction(self.ouv_fichier)
        self.menuFichier.addAction(self.sauv_fichier)
        self.menuFichier.addAction(self.fermer_fichier)
        self.changer_theme.addAction(self.theme_clair)
        self.changer_theme.addAction(self.theme_sombre)
        self.menuA_propos.addAction(self.aide_logiciel)
        self.menuA_propos.addAction(self.a_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.Creer_fiche.menuAction())
        self.menubar.addAction(self.changer_theme.menuAction())
        self.menubar.addAction(self.menuA_propos.menuAction())

        self.retranslateUi(ExercicePython)
        QtCore.QMetaObject.connectSlotsByName(ExercicePython)

    def retranslateUi(self, ExercicePython):
        ExercicePython.setWindowTitle(QtGui.QApplication.translate("ExercicePython", "Python exercice", None, QtGui.QApplication.UnicodeUTF8))
        self.la_enonce.setText(QtGui.QApplication.translate("ExercicePython", "Enoncé : ", None, QtGui.QApplication.UnicodeUTF8))
        self.la_solution.setText(QtGui.QApplication.translate("ExercicePython", "Solution :", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_toutvoir.setText(QtGui.QApplication.translate("ExercicePython", "Tout voir", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_5lignes.setText(QtGui.QApplication.translate("ExercicePython", "voir 5 lignes", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_10lignes.setText(QtGui.QApplication.translate("ExercicePython", "Voir 10 lignes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_nomfiche.setTitle(QtGui.QApplication.translate("ExercicePython", "Exercices", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_deb.setText(QtGui.QApplication.translate("ExercicePython", "Débutant", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_int.setText(QtGui.QApplication.translate("ExercicePython", "Intermédiaire", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_exp.setText(QtGui.QApplication.translate("ExercicePython", "Expert", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("ExercicePython", "fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.Creer_fiche.setTitle(QtGui.QApplication.translate("ExercicePython", "Créer un excercice", None, QtGui.QApplication.UnicodeUTF8))
        self.changer_theme.setTitle(QtGui.QApplication.translate("ExercicePython", "Changer le thème", None, QtGui.QApplication.UnicodeUTF8))
        self.menuA_propos.setTitle(QtGui.QApplication.translate("ExercicePython", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.ouv_fichier.setText(QtGui.QApplication.translate("ExercicePython", "Ouvrir un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.sauv_fichier.setText(QtGui.QApplication.translate("ExercicePython", "Sauvegarder un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.fermer_fichier.setText(QtGui.QApplication.translate("ExercicePython", "Fermer le fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_clair.setText(QtGui.QApplication.translate("ExercicePython", "Thème clair", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_sombre.setText(QtGui.QApplication.translate("ExercicePython", "Thème sombre", None, QtGui.QApplication.UnicodeUTF8))
        self.aide_logiciel.setText(QtGui.QApplication.translate("ExercicePython", "Aide sur le logiciel", None, QtGui.QApplication.UnicodeUTF8))
        self.a_propos.setText(QtGui.QApplication.translate("ExercicePython", "A propos", None, QtGui.QApplication.UnicodeUTF8))

